# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2a6c4458394736c195b8d89700d2ab8fec5c1248e8a06d3b7ae533e93806826059eb3329594bf35d0724f86e444c72cce29139220b927d40f06e2d1b777185e8

test:
  secret_key_base: 684d913ade7deaa353283e9e291e13ca118dbf041c6e0aeab9ec8c650eca0b55e6a6fc588e0813435a486422faf6282a2bccc85d7c6422c5ce0386bfcfb1ede4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
